/// 人物のドット絵（16×16・`.` は透明）。勇者は4方向×歩きの2コマ（右向きは左向きの左右反転）。
enum CharacterArt {
    /// 左向き（横顔。マントは背中側＝右に出る）。
    static let heroLeft1: [String] = [
        "................",
        "......NNNNN.....",
        ".....NNNNNNN....",
        ".....sssNNNN....",
        "....skssssNN....",
        ".....sssssN.....",
        "......sss.......",
        ".....bbbbbrr....",
        ".....bbbbbrrr...",
        ".....sbbbbrrr...",
        ".....bbbbbrrr...",
        ".....nnnnnrr....",
        "......bbbb......",
        "......bbbb......",
        ".....NNN.NN.....",
        "................",
    ]

    static let heroLeft2: [String] = [
        "................",
        "......NNNNN.....",
        ".....NNNNNNN....",
        ".....sssNNNN....",
        "....skssssNN....",
        ".....sssssN.....",
        "......sss.......",
        ".....bbbbbrr....",
        ".....bbbbbrrr...",
        ".....sbbbbrrr...",
        ".....bbbbbrrr...",
        ".....nnnnnrr....",
        ".....bb..bb.....",
        "....bb....bb....",
        "...NNN....NN....",
        "................",
    ]

    static func mirrored(_ rows: [String]) -> [String] {
        rows.map { String($0.reversed()) }
    }

    static let all: [SpriteID: [String]] = [
        .heroLeft1: heroLeft1,
        .heroLeft2: heroLeft2,
        .heroRight1: mirrored(heroLeft1),
        .heroRight2: mirrored(heroLeft2),
        // 上向き（後ろ姿。顔は見えず、マントが背中いっぱい）。
        .heroUp1: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....NNNNNN.....",
            ".....NNNNNN.....",
            ".....sNNNNs.....",
            "......ssss......",
            "....rrrrrrrr....",
            "...rrrrrrrrrr...",
            "...srrrrrrrrs...",
            "...rrrrRRrrrr...",
            "....nnnnnnnn....",
            "....bbb..bbb....",
            "....bbb..bbb....",
            "....NNN..NNN....",
            "................",
        ],
        .heroUp2: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....NNNNNN.....",
            ".....NNNNNN.....",
            ".....sNNNNs.....",
            "......ssss......",
            "....rrrrrrrr....",
            "...rrrrrrrrrr...",
            "...srrrrrrrrs...",
            "...rrrrRRrrrr...",
            "....nnnnnnnn....",
            "....bbb...bbb...",
            "...bbb....bbb...",
            "...NNN.....NNN..",
            "................",
        ],
        .hero1: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....NssssN.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            "....rbbbbbbr....",
            "...rbbbybbbbr...",
            "...sbbbybbbbs...",
            "...rbbbbbbbbr...",
            "....nnnnnnnn....",
            "....bbb..bbb....",
            "....bbb..bbb....",
            "....NNN..NNN....",
            "................",
        ],
        .hero2: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....NssssN.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            "....rbbbbbbr....",
            "...rbbbybbbbr...",
            "...sbbbybbbbs...",
            "...rbbbbbbbbr...",
            "....nnnnnnnn....",
            "....bbb...bbb...",
            "...bbb....bbb...",
            "...NNN.....NNN..",
            "................",
        ],
        .elder: [
            "................",
            "......wwww......",
            ".....wwwwww.....",
            ".....wsssssw....",
            ".....skssksw....",
            ".....wwwwwww....",
            "......wwwww.....",
            "....pppwwwpp....",
            "...ppppwwpppp...",
            "...sppppppppps..",
            "...pppppppppp...",
            "...pppppppppp...",
            "...pppppppppp...",
            "....pppppppp....",
            "....NNN..NNN....",
            "................",
        ],
        .innkeeper: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....NssssN.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            "....wwggggww....",
            "...wwggggggww...",
            "...swggggggws...",
            "...wwggggggww...",
            "....gggggggg....",
            "....aaa..aaa....",
            "....aaa..aaa....",
            "....NNN..NNN....",
            "................",
        ],
        .shopkeeper: [
            "................",
            "......ssss......",
            ".....yyyyyy.....",
            ".....ssssss.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            "....oooooooo....",
            "...oooooooooo...",
            "...soooooooos...",
            "...oooooooooo...",
            "....nnnnnnnn....",
            "....NNN..NNN....",
            "....NNN..NNN....",
            "....kkk..kkk....",
            "................",
        ],
        .villager: [
            "................",
            "......yyyy......",
            ".....yyyyyy.....",
            "....yyssssyy....",
            "....yskssksy....",
            "....yssssssy....",
            "......ssss......",
            ".....rrrrrr.....",
            "....rrrrrrrr....",
            "....srrrrrrs....",
            "....rrrrrrrr....",
            "...rrrrrrrrrr...",
            "...rrrrrrrrrr...",
            "....ss....ss....",
            "....NN....NN....",
            "................",
        ],
        // 五稜郭の奉行。まげと 肩の張った かみしも。
        .magistrate: [
            "................",
            ".......kk.......",
            "......kkkk......",
            ".....kkkkkk.....",
            ".....ssssss.....",
            ".....skssks.....",
            ".....ssssss.....",
            "..BBBBBBBBBBBB..",
            "...BBBwwwwBBB...",
            "....BBBwwBBB....",
            "...sBBBBBBBBs...",
            "....AAAAAAAA....",
            "....AAAAAAAA....",
            "...AAAA..AAAA...",
            "...kkk....kkk...",
            "................",
        ],
        // 港の親方。はちまきに はっぴ、ゴムの長ぐつ。
        .fisherman: [
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....wwwwww.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            "....bbbwwbbb....",
            "...bbbbwwbbbb...",
            "...sbbbbbbbbs...",
            "...bbbbbbbbbb...",
            "....nnnnnnnn....",
            "....BBB..BBB....",
            "....BBB..BBB....",
            "....kkk..kkk....",
            "................",
        ],
        // こども。おとなより 背が ひくい。
        .child: [
            "................",
            "................",
            "................",
            "................",
            "......NNNN......",
            ".....NNNNNN.....",
            ".....skssks.....",
            ".....ssssss.....",
            "......ssss......",
            ".....gggggg.....",
            "....sggggggs....",
            ".....gggggg.....",
            ".....bb..bb.....",
            ".....bb..bb.....",
            ".....NN..NN.....",
            "................",
        ],
        // ハクチョウの ひな。はいいろの わたげ。
        .cygnet: [
            "................",
            "................",
            "................",
            "................",
            "................",
            ".....aaa........",
            "....aaaaa.......",
            "....akaaao......",
            "....aaaaaoo.....",
            ".....aaa........",
            "....aaaaaaaa....",
            "...aaawaaaaaa...",
            "...aaaaaaaaaa...",
            "....aaaaaaaa....",
            "......oo.oo.....",
            "................",
        ],
        // 小樽の ネコ（ミケ）。
        .cat: [
            "................",
            "................",
            "................",
            "................",
            "..w...w.........",
            "..ww.ww.........",
            "..wwwwwo........",
            "..wkwkwo........",
            "..wwnwwoo.....o.",
            "...wwwoooow..oo.",
            "...wwwwwwwoww.o.",
            "...wwwwwoooww.o.",
            "...wwwwwwwwwwo..",
            "...ww.ww.ww.ww..",
            "...ww.ww.ww.ww..",
            "................",
        ],
        // 定山渓の かっぱ。
        .kappa: [
            "................",
            ".....wwwwww.....",
            "....wwcccwww....",
            "....GgggggggG...",
            "...GgwkggwkgG...",
            "...GggggggggG...",
            "...Gggyyyyggg...",
            "....gggyyggg....",
            ".....gggggg.....",
            "....ggGGGGgg....",
            "...gg.GnnG.gg...",
            "...g..GnnG..g...",
            "......gggg......",
            ".....gg..gg.....",
            ".....gg..gg.....",
            "................",
        ],
    ]
}
